server:
  port: 8888

logging:
  config: classpath:logback-spring.xml

cors:
  allow: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/docs #jdbc:postgresql://db:5432/docs
    username: postgres
    password: 1234
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath*:/migrations/db.changelog-master.yml
    default-schema: public

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:29092 #kafka:9092